#!/usr/bin/env python3
"""
Generate the three Ref2VA clip prompts and the sequence JSON for a dish.

For any new dish config, first build the recipe-grounded package described in
prompts/COOKING_PROMPT_PRODUCTION_STANDARD.md. Do not create dish configs from
memory when real recipe steps, temperatures, textures, and doneness matter.

The three-shot shape here is not a guess. It is the one that measured 2.5%,
0.0% and 0.8% camera flip rates on the beef, kelp and tomato ads, against 33.6%
for the version that preceded it. Every rule it encodes was paid for:

  shot 1  wide establishing, one committed continuous push, ends on the
          ingredients being readable
  shot 2  medium over the work surface, locked off, one gathering action, the
          knife explicitly at rest. Never a tight close-up of a hand working a
          tool: at 4 steps that produced a knife in two pieces and a cabbage
          that changed species, and 8 steps improved it without curing it
  shot 3  locked close-up, one continuous action carried to a physical endpoint.
          Never a state to hold; the beat that ended on "steam rises" left the
          model 40 frames of nothing and it filled them with 45% frame-to-frame
          direction reversals

Reference binding is positional and clips 2 and 3 shift by one, because the
sequence runner prepends the previous clip's last frame. Getting that wrong
produces a plausible-looking clip with every reference attached to the wrong
thing, so the sequence is generated here too rather than written by hand.

Usage:
  python generate_clip_prompts.py --all
  python generate_clip_prompts.py --all --check
  python generate_clip_prompts.py kungpao_chicken
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent
CONFIG_DIR = ROOT / "prompts" / "dish_configs"
PROMPT_DIR = ROOT / "prompts" / "h3_3x5_1080"
SEQ_DIR = ROOT / "sequences"
ASSET_DIRS = {p.name.split("_", 1)[1]: p for p in (ROOT / "outputs" / "reference_assets").iterdir()
              if p.is_dir()} if (ROOT / "outputs" / "reference_assets").is_dir() else {}

KINDS = ["character_scene", "prep_state", "cook_state", "hero_state"]

NEG_COMMON = ("distorted faces, extra fingers, invented text, captions, watermarks, "
              "floating logos, camera shake, and scene jumps")


def asset_rel(cfg: dict, kind: str) -> str:
    """Path to a generated reference, relative to sequences/.

    Assets generated by generate_dish_assets.py are named {slug}_{kind}.png. The
    two dishes that predate that script are not, so a config may name its files
    explicitly in "assets" rather than have them renamed out from under the
    sequences that already reference them.
    """
    name = cfg.get("assets", {}).get(kind, f"{cfg['slug']}_{kind}") + ".png"
    for group in (ROOT / "outputs" / "reference_assets").iterdir():
        candidate = group / name
        if candidate.is_file():
            return "../" + candidate.relative_to(ROOT).as_posix()
    raise SystemExit(f"reference not found: {name}")


def subject2(cfg: dict) -> str:
    """The <Subject 2> definition line, for dishes with a second person in frame."""
    return f"\n<Subject 2> is {cfg['cook2']}." if cfg.get("cook2") else ""


def fully_preserved2(cfg: dict) -> str:
    """The <Subject 2> retention line. Every marker must name every subject."""
    return ("\n<Subject 2>: fully_preserved. Same face, build and clothing throughout, "
            "and never handling anything hot.") if cfg.get("cook2") else ""


def product_rel(cfg: dict) -> str:
    p = ROOT / "sample_pictures" / cfg["product_dir"] / cfg["product_file"]
    if not p.is_file():
        raise SystemExit(f"product image not found: {p}")
    return "../" + p.relative_to(ROOT).as_posix()


def beat(cfg: dict, key: str, default: str) -> str:
    """The action inside a shot, which the recipe decides.

    The camera grammar around it does not move: shot 1 of a clip establishes,
    shot 2 carries the single committed push, shot 3 locks off and ends on a
    physical stop. Those measured 2.5%, 0.0% and 0.8% flip rates and are not
    a dish's business. What happens in front of the lens is.

    The generic defaults describe a stir-fry, because that is what the first six
    dishes were. They are wrong for a dish that is simmered for an hour, or one
    that is fried, drained and then tossed. A config supplies "beats" to say what
    its recipe actually does; anything it omits falls back to the generic beat.
    """
    return (cfg.get("beats") or {}).get(key) or default


def clip01(cfg: dict) -> str:
    c = cfg
    # Overridable because the default beat tips an ingredient into a vessel, and a
    # tray of egg tarts is placed, not tipped.
    c1s3 = beat(c, "c1s3",
                "The hands of <Subject 1> enter from the top of frame carrying the ingredient, "
                "tip it in once, and withdraw straight up out of frame empty.")
    # <Picture 3> is the working state, so the photograph shows the vessel FULL of a
    # nearly finished dish. Pointing the model at it and saying "the vessel, already
    # hot" got a wok of finished food with raw mince being tipped onto it - the
    # reference beat the wording, the same way the product photo's label did. The
    # vessel's starting state now has to be stated positively, and <Picture 3> is
    # explicitly reduced to the vessel itself for this shot.
    vessel_start = c.get("vessel_start", "empty and already hot, with nothing in it yet")
    shot3 = c.get("clip01_shot3") or (
        "[Shot 3] At 00:03.400, the shot cuts to a locked-off close-up at cooking height. "
        f"The vessel of <Picture 3> fills the lower two thirds of frame over its heat source, "
        f"{vessel_start}. <Picture 3> supplies this vessel's shape and position only, never its "
        f"contents. {c1s3} {c['first_heat']} "
        "The camera does not move at any point in this shot.")
    return f"""subject_definitions:
<Subject 1> is {c['cook']}, working at the counter of the kitchen in <Picture 1>.{subject2(c)}
<Picture 1> is the cook and kitchen bible: {c['kitchen']}.
<Picture 2> is the prep state, which defines {c['prep_defines']}: {c['prep_subject']}.
<Picture 3> is the working state: {c['cook_subject']}.
<Picture 4> is the finished hero state, used here only as a colour and texture target.
<Picture 5> is the product image: {c['product_desc']}.
<Picture 6> is the ASIAN GROCER ONLINE / POWERED BY UMALL brand lockup, allowed only as a real printed card standing on the counter.

summary:
reference generation. A five-second vertical premium cooking commercial, clip 01 of a three-clip sequence for {c['dish_en']}. <Subject 1> and the kitchen of <Picture 1> establish the setting, <Picture 5> supplies the raw ingredient identity, and <Picture 2> supplies the already-prepared components that prove real preparation happened. The clip carries the ingredients from the counter to first heat, ending as {c['story'][0]}, so clip 02 can open on cooking already under way. <Picture 4> is not staged here.

retention_analysis:
<Subject 1>: fully_preserved. Same face, build and clothing throughout.{fully_preserved2(c)}
<Picture 1>: attribute_transfer. Kitchen layout, light direction and material palette carry over; exact framing does not.
<Picture 2>: fully_preserved. Every component keeps the size and cut this image defines.
<Picture 3>: weak_reference. Only the vessel's shape, material and position carry over. Its contents do not: the vessel is empty when this clip begins, and the food that image shows is where clip 02 ends up, not where clip 01 starts.
<Picture 4>: weak_reference. Colour and texture target only, not composed in frame.
<Picture 5>: fully_preserved. The raw ingredient keeps its colour and surface exactly.
<Picture 6>: weak_reference. May appear once as a small printed card far back on the counter, never as an overlay.

detailed_description:
[Shot 1] Medium shot at eye level, 50mm feel. <Subject 1> stands at the counter of the kitchen from <Picture 1>, the cooking vessel of <Picture 3> at their right. Laid out in front of them are the raw ingredient of <Picture 5> and the prepared components of <Picture 2>, with the small printed card of <Picture 6> far back near the wall, legible but never dominant. Directional light rakes across the ingredient so its surface reads clearly. {beat(c, "c1s1", "<Subject 1> draws the ingredients toward them across the counter in one movement.")}{" " + c["cook2_open"] if c.get("cook2_open") else ""} The camera pushes in toward the counter steadily and continuously across the whole shot, one single move that never pauses or reverses. The shot ends with every component readable in frame.

[Shot 2] At 00:01.600, the shot cuts to a medium-close shot over the work surface, high three-quarter angle, 50mm feel, holding both forearms of <Subject 1> and the whole surface. On it are the prepared components of <Picture 2>, exactly as that image defines them. Any knife rests flat at the far side and is never lifted. {beat(c, "c1s2", "Both hands of <Subject 1> gather the components into one pile and slide them to the near edge, beside the ingredient of <Picture 5>.")} The camera does not move and the focus does not rack. The shot ends with the prepared components and the raw ingredient together in the near half of frame, both sharp.

{shot3}

Preserve across all shots: the identity of <Subject 1>, realistic hands, the ingredient of <Picture 5>, the component sizes of <Picture 2>, the vessel of <Picture 3>, and one coherent colour grade. Avoid {c['negatives_global']}, {NEG_COMMON}.

overall_soundscape:
{c['sound_01']}

non_diegetic_music:
{c['music']} It sits under the physical sounds and lifts as the ingredient meets heat, resolving on an unfinished phrase so clip 02 can continue.
"""


def clip02(cfg: dict) -> str:
    c = cfg
    return f"""subject_definitions:
<Picture 1> is the final frame of clip 01, showing the cooking vessel with the ingredient just added and the first heat rising from it.
<Subject 1> is {c['cook']}.
<Picture 2> is the cook and kitchen bible: {c['kitchen']}.
<Picture 3> is the prep state: {c['prep_subject']}.
<Picture 4> is the working state, the target of this clip: {c['cook_subject']}.
<Picture 5> is the finished hero state, the colour and texture target.
<Picture 6> is the product image: {c['product_desc']}.

summary:
reference generation. A five-second vertical premium cooking commercial, clip 02 of three, for {c['dish_en']}. It opens on the state <Picture 1> left behind and carries the cook to the established working state of <Picture 4>, which is the single teaching point: {c['story'][1]}. <Subject 1> appears only through their hands. The clip ends mid-cook so clip 03 can begin plating.

retention_analysis:
<Picture 1>: fully_preserved. Same vessel, same heat, same ingredient, continuing without a jump.
<Subject 1>: fully_preserved. Hands and forearms only, matching skin tone and sleeves.
<Picture 2>: attribute_transfer. Light direction and material palette carry over; framing does not.
<Picture 3>: fully_preserved. Components keep the size and cut defined there.
<Picture 4>: fully_preserved. The vessel, the state of the ingredient and the heat source are the target of this clip.
<Picture 5>: partially_preserved. Colour and texture are matched; the plated dish is not staged.
<Picture 6>: fully_preserved. The ingredient keeps its identity, now partly cooked.

detailed_description:
{c.get("clip02_shot1") or '''[Shot 1] Locked-off close-up at cooking height, 50mm feel, continuing directly from <Picture 1>. The vessel of <Picture 4> fills the lower two thirds of frame over its heat source, which stays visible at the bottom of frame throughout. What went in during clip 01 is already colouring and moving with the heat. The hands of <Subject 1> enter from the top of frame carrying the remaining prepared components from <Picture 3>, exactly the size and cut that image defines, tip them in once among what is already cooking, and withdraw straight up out of frame empty. The added components settle against the hot surface, and the sound and movement of the cook change audibly as they land. The camera does not move at any point in this shot, and the framing does not drift.'''}

[Shot 2] At 00:01.600, the shot cuts to a close-up over the vessel, high three-quarter angle, 50mm feel. Over the shot the cook visibly advances: {c['transform']} No hand enters this shot. The camera pushes in toward the surface steadily and continuously across the whole shot, one single move that never pauses or reverses. The shot ends with the ingredient in the state of <Picture 4>, filling most of the frame.

[Shot 3] At 00:03.400, the shot cuts to a locked-off macro close-up. {c['lift']} The camera does not move and the focus does not rack. The shot ends with the piece raised and still dripping.

Preserve across all shots: realistic hands, the ingredient of <Picture 6> in its cooking state, the components of <Picture 3>, the vessel and heat source of <Picture 4>, and one coherent colour grade. Avoid {c['cook_negatives']}, {c['negatives_global']}, {NEG_COMMON}.

overall_soundscape:
{c['sound_02']}

non_diegetic_music:
{c['music']} It stays under the physical sounds and lifts slightly as the piece is lifted clear, resolving on an unfinished phrase so clip 03 can continue.
"""


def clip03(cfg: dict) -> str:
    c = cfg
    return f"""subject_definitions:
<Picture 1> is the final frame of clip 02, showing a piece of the dish lifted clear of the vessel with sauce or juices running from it.
<Subject 1> is {c['cook']}.{subject2(c)}
<Picture 2> is the cook and kitchen bible: {c['kitchen']}.
<Picture 3> is the working state: {c['cook_subject']}.
<Picture 4> is the finished hero state, the target of this clip: {c['hero_subject']}.
<Picture 5> is the product image: {c['product_desc']}.
<Picture 6> is the ASIAN GROCER ONLINE / POWERED BY UMALL brand lockup, allowed only as a real printed card standing on the table.

summary:
reference generation. A five-second vertical premium cooking commercial, clip 03 of three, the closing beat for {c['dish_en']}. It continues from <Picture 1> and carries the dish from the vessel to the table, landing on the hero state of <Picture 4>. The product job is that the ingredient of <Picture 5> stays identifiable in its finished form. The clip ends on a still composed hero frame that can be held or trimmed in the edit.

retention_analysis:
<Picture 1>: fully_preserved. Same vessel, same dish, continuing without a jump.
<Subject 1>: fully_preserved. Same hands; face may enter softly at the end.{fully_preserved2(c)}
<Picture 2>: attribute_transfer. Light direction and material palette carry over; framing does not.
<Picture 3>: partially_preserved. The vessel travels to the table and stays recognisable, but leaves the heat.
<Picture 4>: fully_preserved. The plating, the surface texture and the setting are the target of this clip.
<Picture 5>: fully_preserved. The ingredient keeps its identity in cooked form.
<Picture 6>: weak_reference. May appear once as a small printed card at the back of the table, never as an overlay.

detailed_description:
[Shot 1] Locked-off close food angle, 50mm feel, continuing directly from <Picture 1>. The vessel of <Picture 3> sits at the left of frame, the serving dish of <Picture 4> waiting at the right on the table. {c['plate']} The camera does not move at any point in this shot. The shot ends on the filled dish with individual pieces clearly visible.

[Shot 2] At 00:01.600, the shot cuts to a close hero food angle over the dish, 50mm feel. {beat(c, "c3s2", "The hand of <Subject 1> enters from the top of frame holding a small dish of garnish, scatters it once across the surface in a single pass, and withdraws straight up out of frame. The garnish lands bright against the finished dish.")} Steam rises steadily behind. The setting of <Picture 4> is established around it. The camera pushes in toward the dish steadily and continuously across the whole shot, one single move that never pauses or reverses. The shot ends with the finished dish centred and sharp.

[Shot 3] At 00:03.400, the shot cuts to a locked-off medium close-up of the table. The finished dish of <Picture 4> sits in the foreground, the small printed card of <Picture 6> standing far back near the edge, legible but never dominant, <Subject 1> present behind in soft focus.{" " + c["cook2_close"] if c.get("cook2_close") else ""} {c['final_lift']} The camera does not move and the focus does not rack. The shot ends with the piece held above the finished dish.

Preserve across all shots: the identity of <Subject 1>, realistic hands, the ingredient of <Picture 5> in finished form, the plating and setting of <Picture 4>, and one coherent colour grade. Avoid {c['negatives_global']}, {NEG_COMMON}.

overall_soundscape:
{c['sound_03']}

non_diegetic_music:
{c['music']} It lifts as the garnish lands and settles into a complete final cadence as the piece is lifted.
"""


def build_sequence(cfg: dict) -> dict:
    slug = cfg["slug"]
    a = {k: asset_rel(cfg, k) for k in KINDS}
    product = product_rel(cfg)
    logo = "../company_logo/AGO.png"
    return {
        "sequence_id": f"{slug}_3x5_native1080",
        "server": "http://127.0.0.1:8189",
        "defaults": {
            "mode": "r2v", "width": 1088, "height": 1920, "duration": 5.0,
            "steps": 8, "turbo": True, "turbo_low_vram": True, "no_audio": True,
            "ref_image_size": "match", "poll": 10, "timeout": 10800,
        },
        "clips": [
            {"id": "clip-01-prep-to-heat",
             "prompt_file": f"../prompts/h3_3x5_1080/{slug}_clip_01.md",
             "ref_images": [a["character_scene"], a["prep_state"], a["cook_state"],
                            a["hero_state"], product, logo],
             "seed": cfg["seed_base"] + 1,
             "prefix": f"sequence/{slug}_3x5_native1080/clip-01"},
            {"id": "clip-02-cook",
             "prompt_file": f"../prompts/h3_3x5_1080/{slug}_clip_02.md",
             "use_previous_last_frame_as_ref": True,
             "ref_images": [a["character_scene"], a["prep_state"], a["cook_state"],
                            a["hero_state"], product],
             "seed": cfg["seed_base"] + 2,
             "prefix": f"sequence/{slug}_3x5_native1080/clip-02"},
            {"id": "clip-03-serving-hero",
             "prompt_file": f"../prompts/h3_3x5_1080/{slug}_clip_03.md",
             "use_previous_last_frame_as_ref": True,
             "ref_images": [a["character_scene"], a["cook_state"],
                            a["hero_state"], product, logo],
             "seed": cfg["seed_base"] + 3,
             "prefix": f"sequence/{slug}_3x5_native1080/clip-03"},
        ],
        "final": {
            "filename": f"{slug}_3x5_native_1080x1920.mp4",
            "concat_mode": "both",
            "crop": {"width": 1080, "height": 1920, "x": 4, "y": 0},
            "crf": 16, "preset": "medium", "keep_audio": False,
        },
    }


def check_rendered_prompts(cfg: dict) -> list[tuple[str, list[str]]]:
    """Render prompts without writing production files, then run the validator."""
    from prompts.validate_prompt import check, refs_for_clip

    seq = build_sequence(cfg)
    funcs = ((1, clip01), (2, clip02), (3, clip03))
    failures: list[tuple[str, list[str]]] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = pathlib.Path(tmp)
        for index, (n, fn) in enumerate(funcs):
            path = tmp_dir / f"{cfg['slug']}_clip_0{n}.md"
            path.write_text(fn(cfg), encoding="utf-8", newline="\n")
            problems = check(path, refs_for_clip(seq["clips"][index]))
            if problems:
                failures.append((path.name, problems))
    return failures


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("slugs", nargs="*")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--check", action="store_true",
                        help="render to a temporary directory and validate without writing output files")
    args = parser.parse_args(argv)

    available = sorted(p.stem for p in CONFIG_DIR.glob("*.json"))
    slugs = available if args.all else args.slugs
    if not slugs:
        parser.error("name a dish, or use --all")

    if args.check:
        failed = 0
        for slug in slugs:
            cfg = json.loads((CONFIG_DIR / f"{slug}.json").read_text(encoding="utf-8"))
            label = f"{cfg['slug']} ({cfg['dish_en']})"
            failures = check_rendered_prompts(cfg)
            if not failures:
                print(f"  ok   {label}: rendered prompts validate")
                continue
            failed += 1
            print(f"  FAIL {label}")
            for name, problems in failures:
                print(f"       {name}")
                for problem in problems:
                    print(f"         ! {problem}")
        return 1 if failed else 0

    PROMPT_DIR.mkdir(parents=True, exist_ok=True)
    for slug in slugs:
        cfg = json.loads((CONFIG_DIR / f"{slug}.json").read_text(encoding="utf-8"))
        for n, fn in ((1, clip01), (2, clip02), (3, clip03)):
            path = PROMPT_DIR / f"{slug}_clip_0{n}.md"
            path.write_text(fn(cfg), encoding="utf-8", newline="\n")
        seq_path = SEQ_DIR / f"{slug}_3x5_1080.json"
        seq_path.write_text(json.dumps(build_sequence(cfg), ensure_ascii=False, indent=2) + "\n",
                            encoding="utf-8", newline="\n")
        print(f"  {cfg['slug']}: 3 prompts + {seq_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
